version: '3'
services:
  digdag:
    build:
      context: ./digdag
      dockerfile: ./Dockerfile
    ports:
      - "65432:65432"
    volumes:
      - /tmp:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
      - ./log:/var/log/digdag
    environment:
      DIGDAG_PORT: 65432
      DB_TYPE: postgresql
      DB_USER: digdag
      DB_PASSWORD: digdag
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: digdag
    links:
      - postgres
    restart: always
    privileged: true

  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: digdag
      POSTGRES_USER: digdag
      POSTGRES_DB: digdag
    volumes:
      - db-data:/var/lib/postgresql
    command: postgres -c 'max_connections=512'
volumes:
  db-data:
    driver: local
